### ISSUE TITLE
Show Entries (Food Tracking)

### ISSUE THREAD

**Issue by MelindaCardenas** [my-carbon-tracker/my-carbon-footprint-server#62]

**Comment by e-mbrown** [comment]
Table with food and servings, allowing editing to be done as well as the removal of pieces of the entry.
>Alter the food tracker table to allow an entries
>Send the entries to DB
>Render entries on emission page after query

**Comment by e-mbrown** [comment]
Finished and added to frontend. Further styling will be needed at a later point
